### Spring properties
# HTTP Server (Tomcat) Port
server: 
  port: 2346
  
  
#oracle db settings details
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: mutual
    password: fund
    driver-class-name: oracle.jdbc.OracleDriver
    
  application:
    name: Manager-microservice  
    
# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:2345/eureka/


  
  

